// <auto-generated />
using System;
using LimitsAndTransactionsApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LimitsAndTransactionsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LimitsAndTransactionsApi.Models.Entity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("encrypted_api_path");

                    b.HasKey("Id");

                    b.ToTable("api_key");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d05eca88-8ddb-4576-b2a8-7415f358364a"),
                            Active = true,
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 10, 27, 10, 19, 1, 124, DateTimeKind.Unspecified).AddTicks(9356), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "twelve",
                            EncryptedApiPath = "F5z8tDG0AI0Xon4zLcuLZsXXPAbiMkYDQJHBzYUOLXGHRFDqq4AWvWxil+mRt0+w"
                        });
                });

            modelBuilder.Entity("LimitsAndTransactionsApi.Models.Entity.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("close");

                    b.Property<string>("CurrencyPair")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_pair");

                    b.Property<DateTimeOffset>("DateTimeRate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("datetime_rate");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rate");

                    b.HasKey("Id");

                    b.ToTable("exchange_rates");
                });
#pragma warning restore 612, 618
        }
    }
}
